version: '3.9'
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: 'auto_strategy'
      POSTGRES_USER: 'admin'
      POSTGRES_PASSWORD: 'password'
      PGDATA: '/var/lib/postgresql/data/pgdata'
    volumes:
#      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      - pg-data:/var/lib/postgresql/data
    ports:
      - '6432:5432'

volumes:
  pg-data:
